-- MySQL Script generated by MySQL Workbench
-- Mon 16 May 2016 02:49:25 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema opendsa_lti
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `opendsa_lti` ;

-- -----------------------------------------------------
-- Schema opendsa_lti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opendsa_lti` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `opendsa_lti` ;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`time_zones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`time_zones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`time_zones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `zone` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `display_as` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`global_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`global_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`global_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `can_manage_all_courses` TINYINT(1) NOT NULL DEFAULT '0',
  `can_edit_system_configuration` TINYINT(1) NOT NULL DEFAULT '0',
  `builtin` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `encrypted_password` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `reset_password_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `reset_password_sent_at` DATETIME NULL DEFAULT NULL,
  `remember_created_at` DATETIME NULL DEFAULT NULL,
  `sign_in_count` INT(11) NOT NULL DEFAULT '0',
  `current_sign_in_at` DATETIME NULL DEFAULT NULL,
  `last_sign_in_at` DATETIME NULL DEFAULT NULL,
  `current_sign_in_ip` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_sign_in_ip` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `confirmation_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `confirmed_at` DATETIME NULL DEFAULT NULL,
  `confirmation_sent_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `global_role_id` INT(11) NOT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `time_zone_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `users_time_zone_id_fk`
    FOREIGN KEY (`time_zone_id`)
    REFERENCES `opendsa_lti`.`time_zones` (`id`),
  CONSTRAINT `users_global_role_id_fk`
    FOREIGN KEY (`global_role_id`)
    REFERENCES `opendsa_lti`.`global_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_users_on_email` ON `opendsa_lti`.`users` (`email` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_users_on_slug` ON `opendsa_lti`.`users` (`slug` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_users_on_confirmation_token` ON `opendsa_lti`.`users` (`confirmation_token` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_users_on_reset_password_token` ON `opendsa_lti`.`users` (`reset_password_token` ASC);

SHOW WARNINGS;
CREATE INDEX `index_users_on_global_role_id` ON `opendsa_lti`.`users` (`global_role_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_users_on_time_zone_id` ON `opendsa_lti`.`users` (`time_zone_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`terms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`terms` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`terms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `season` INT(11) NOT NULL,
  `starts_on` DATE NOT NULL,
  `ends_on` DATE NOT NULL,
  `year` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '# Represents an academic term or semester, which indicates the time period\n# for one or more course offerings.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_terms_on_slug` ON `opendsa_lti`.`terms` (`slug` ASC);

SHOW WARNINGS;
CREATE INDEX `index_terms_on_starts_on` ON `opendsa_lti`.`terms` (`starts_on` ASC);

SHOW WARNINGS;
CREATE INDEX `index_terms_on_year_and_season` ON `opendsa_lti`.`terms` (`year` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`organizations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`organizations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `abbreviation` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '# Represents a university, college, school, or other organization that\n# has courses.';

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_organizations_on_name` ON `opendsa_lti`.`organizations` (`name` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_organizations_on_slug` ON `opendsa_lti`.`organizations` (`slug` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`courses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`courses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `number` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `organization_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `creator_id` INT(11) NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `courses_organization_id_fk`
    FOREIGN KEY (`organization_id`)
    REFERENCES `opendsa_lti`.`organizations` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '# Represents a course at a university; akin to the course\'s catalog\n# description.  A course may have one or more course offerings in any\n# specific term.';

SHOW WARNINGS;
CREATE INDEX `index_courses_on_organization_id` ON `opendsa_lti`.`courses` (`organization_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_courses_on_slug` ON `opendsa_lti`.`courses` (`slug` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`late_policies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`late_policies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`late_policies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `late_days` INT(2) NOT NULL,
  `late_percent` INT(2) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `opendsa_lti`.`late_policies` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`course_offerings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`course_offerings` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`course_offerings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_id` INT(11) NOT NULL,
  `term_id` INT(11) NOT NULL,
  `label` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `self_enrollment_allowed` TINYINT(1) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `cutoff_date` DATE NULL DEFAULT NULL,
  `lms_course_code` VARCHAR(45) NULL DEFAULT NULL,
  `lms_course_id` INT(11) NULL DEFAULT NULL,
  `late_policy_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `course_offerings_term_id_fk`
    FOREIGN KEY (`term_id`)
    REFERENCES `opendsa_lti`.`terms` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `course_offerings_course_id_fk`
    FOREIGN KEY (`course_id`)
    REFERENCES `opendsa_lti`.`courses` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_course_offerings_late_policies1`
    FOREIGN KEY (`late_policy_id`)
    REFERENCES `opendsa_lti`.`late_policies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'Represents a single section (or offering) of a course in a specific term.';

SHOW WARNINGS;
CREATE INDEX `index_course_offerings_on_course_id` ON `opendsa_lti`.`course_offerings` (`course_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_course_offerings_on_term_id` ON `opendsa_lti`.`course_offerings` (`term_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_course_offerings_late_policies1_idx` ON `opendsa_lti`.`course_offerings` (`late_policy_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`course_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`course_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`course_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `can_manage_course` TINYINT(1) NOT NULL DEFAULT '0',
  `can_manage_assignments` TINYINT(1) NOT NULL DEFAULT '0',
  `can_grade_submissions` TINYINT(1) NOT NULL DEFAULT '0',
  `can_view_other_submissions` TINYINT(1) NOT NULL DEFAULT '0',
  `builtin` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`course_enrollments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`course_enrollments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`course_enrollments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `course_offering_id` INT(11) NOT NULL,
  `course_role_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `course_enrollments_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `opendsa_lti`.`users` (`id`),
  CONSTRAINT `course_enrollments_course_offering_id_fk`
    FOREIGN KEY (`course_offering_id`)
    REFERENCES `opendsa_lti`.`course_offerings` (`id`),
  CONSTRAINT `course_enrollments_course_role_id_fk`
    FOREIGN KEY (`course_role_id`)
    REFERENCES `opendsa_lti`.`course_roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `index_course_enrollments_on_user_id_and_course_offering_id` ON `opendsa_lti`.`course_enrollments` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_course_enrollments_on_course_offering_id` ON `opendsa_lti`.`course_enrollments` (`course_offering_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_course_enrollments_on_course_role_id` ON `opendsa_lti`.`course_enrollments` (`course_role_id` ASC);

SHOW WARNINGS;
CREATE INDEX `index_course_enrollments_on_user_id` ON `opendsa_lti`.`course_enrollments` (`user_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`errors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`errors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`errors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usable_type` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `usable_id` INT(11) NULL DEFAULT NULL,
  `class_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `message` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `trace` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `target_url` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `referer_url` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `params` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_agent` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `index_errors_on_class_name` ON `opendsa_lti`.`errors` (`class_name` ASC);

SHOW WARNINGS;
CREATE INDEX `index_errors_on_created_at` ON `opendsa_lti`.`errors` (`created_at` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_book_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_book_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_book_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `can_modify` TINYINT(1) NULL DEFAULT 1,
  `can_compile` TINYINT(1) NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Represent users roles with a book configuration';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_book_owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_book_owners` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_book_owners` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cnf_book_role_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cnf_book_users_cnf_book_roles1`
    FOREIGN KEY (`cnf_book_role_id`)
    REFERENCES `opendsa_lti`.`inst_book_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cnf_book_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '# Represents a many-to-many relationship between users and book configurations\n# Admins can clone book configuration and give permission to Instructors to modify the cloned configuration and/or recompile it';

SHOW WARNINGS;
CREATE INDEX `fk_cnf_book_users_cnf_book_roles1_idx` ON `opendsa_lti`.`inst_book_owners` (`cnf_book_role_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_cnf_book_users_users1_idx` ON `opendsa_lti`.`inst_book_owners` (`users_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_books` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_books` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `book_url` VARCHAR(80) NOT NULL COMMENT 'book main url page in OpenDSA-Server. \nThis page may show basic dashboard for book information, \nit might show a gradebook. ',
  `course_offering_id` INT(11) NOT NULL,
  `cnf_book_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `cnf_book_users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_opendsa_books_course_offerings1`
    FOREIGN KEY (`course_offering_id`)
    REFERENCES `opendsa_lti`.`course_offerings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inst_books_cnf_book_users1`
    FOREIGN KEY (`cnf_book_users_id`)
    REFERENCES `opendsa_lti`.`inst_book_owners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Represents a book Instance which essentially means a compiled book (generated files under /Books directory) \nand likes to corresponding LMS chapters/modules/sections/exercises (all likes stored as Ids). ';

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_books_course_offerings1_idx` ON `opendsa_lti`.`inst_books` (`course_offering_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_inst_books_cnf_book_users1_idx` ON `opendsa_lti`.`inst_books` (`cnf_book_users_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_chapters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_chapters` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_chapters` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `short_display_name` VARCHAR(45) NULL DEFAULT NULL,
  `book_id` INT(11) NOT NULL,
  `position` INT(11) NOT NULL,
  `lms_chapter_id` INT(11) NULL DEFAULT NULL COMMENT 'canvas module_id',
  `lms_assignment_group_id` INT(11) NULL DEFAULT NULL COMMENT 'canvas assignment_group_id',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_refs_id_19a809ad`
    FOREIGN KEY (`book_id`)
    REFERENCES `opendsa_lti`.`inst_books` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `book_id` ON `opendsa_lti`.`inst_chapters` (`book_id` ASC);

SHOW WARNINGS;
CREATE INDEX `opendsa_bookchapter_752eb95b` ON `opendsa_lti`.`inst_chapters` (`book_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`modules` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`modules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NOT NULL,
  `short_display_name` VARCHAR(50) NOT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_chapter_modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_chapter_modules` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_chapter_modules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cnf_chapter_id` INT(11) NOT NULL,
  `cnf_module_id` INT(11) NOT NULL,
  `module_position` INT(11) NULL DEFAULT NULL COMMENT 'Module order wthin a chapter',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `inst_chapters_id` INT(11) NOT NULL,
  `inst_modules_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cnf_chapter_modules_inst_chapters1`
    FOREIGN KEY (`inst_chapters_id`)
    REFERENCES `opendsa_lti`.`inst_chapters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cnf_chapter_modules_inst_modules1`
    FOREIGN KEY (`inst_modules_id`)
    REFERENCES `opendsa_lti`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '# Represents a many-to-many relationship between cnf_chapters and cnf_modules,\n# capturing the notion of chapter-specific list of modules.';

SHOW WARNINGS;
CREATE INDEX `fk_cnf_chapter_modules_inst_chapters1_idx` ON `opendsa_lti`.`inst_chapter_modules` (`inst_chapters_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_cnf_chapter_modules_inst_modules1_idx` ON `opendsa_lti`.`inst_chapter_modules` (`inst_modules_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_sections` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_sections` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `short_display_name` VARCHAR(50) NOT NULL,
  `name` LONGTEXT NOT NULL,
  `inst_module_id` INT(11) NOT NULL,
  `position` INT(11) NULL DEFAULT NULL,
  `gradable` TINYINT(1) NULL DEFAULT 0,
  `soft_deadline` DATETIME NULL DEFAULT NULL,
  `hard_deadline` DATETIME NULL DEFAULT NULL COMMENT 'by default hard_deadline = soft_deadline + late_policies.late_days ',
  `time_limit` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `cnf_chapter_modules_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_odsa_module_sections_odsa_modules1`
    FOREIGN KEY (`inst_module_id`)
    REFERENCES `opendsa_lti`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inst_sections_cnf_chapter_modules1`
    FOREIGN KEY (`cnf_chapter_modules_id`)
    REFERENCES `opendsa_lti`.`inst_chapter_modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '# captures exercise specific configuration for a book instance like due dates.\n# users will not be allowed to change the basic book configurations (points, threshold, required) in this stage. The proper way to change these parameters is to change the book configuration and recompile.';

SHOW WARNINGS;
CREATE INDEX `fk_odsa_module_sections_odsa_modules1_idx` ON `opendsa_lti`.`inst_sections` (`inst_module_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_inst_sections_cnf_chapter_modules1_idx` ON `opendsa_lti`.`inst_sections` (`cnf_chapter_modules_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_student_extensions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_student_extensions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_student_extensions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `inst_sections_id` INT(11) NOT NULL,
  `soft_deadline` DATETIME NULL DEFAULT NULL,
  `hard_deadline` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `time_limit` INT(11) NULL DEFAULT NULL,
  `opening_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `student_extensions_user_id_fk0`
    FOREIGN KEY (`user_id`)
    REFERENCES `opendsa_lti`.`users` (`id`),
  CONSTRAINT `fk_odsa_student_extensions_inst_sections1`
    FOREIGN KEY (`inst_sections_id`)
    REFERENCES `opendsa_lti`.`inst_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SHOW WARNINGS;
CREATE INDEX `index_student_extensions_on_user_id` ON `opendsa_lti`.`odsa_student_extensions` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_odsa_student_extensions_inst_sections1_idx` ON `opendsa_lti`.`odsa_student_extensions` (`inst_sections_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`lms_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`lms_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`lms_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`lms_instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`lms_instance` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`lms_instance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  `lms_type_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lms_instance_lms_types1`
    FOREIGN KEY (`lms_type_id`)
    REFERENCES `opendsa_lti`.`lms_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_lms_instance_lms_types1_idx` ON `opendsa_lti`.`lms_instance` (`lms_type_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`lms_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`lms_access` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`lms_access` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  `lms_instance_id` INT NOT NULL,
  `access_token` VARCHAR(150) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_lms_access_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lms_access_lms_instance1`
    FOREIGN KEY (`lms_instance_id`)
    REFERENCES `opendsa_lti`.`lms_instance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_lms_access_users1_idx` ON `opendsa_lti`.`lms_access` (`users_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_lms_access_lms_instance1_idx` ON `opendsa_lti`.`lms_access` (`lms_instance_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`exercises` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`exercises` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `short_display_name` VARCHAR(45) NULL DEFAULT NULL,
  `ex_type` VARCHAR(50) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Lockup table for list of available exercises.\nNote: exercise name should be unique';

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `opendsa_lti`.`exercises` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`inst_book_section_exercises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`inst_book_section_exercises` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`inst_book_section_exercises` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inst_book_id` INT(11) NOT NULL,
  `points` DECIMAL(5,2) NOT NULL,
  `inst_section_id` INT(11) NOT NULL,
  `cnf_exercise_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_refs_id_1d50a4ed`
    FOREIGN KEY (`inst_book_id`)
    REFERENCES `opendsa_lti`.`inst_books` (`id`),
  CONSTRAINT `fk_opendsa_bookmoduleexercise_odsa_module_sections1`
    FOREIGN KEY (`inst_section_id`)
    REFERENCES `opendsa_lti`.`inst_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inst_book_section_exercises_cnf_exercises1`
    FOREIGN KEY (`cnf_exercise_id`)
    REFERENCES `opendsa_lti`.`exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `book_id` ON `opendsa_lti`.`inst_book_section_exercises` (`inst_book_id` ASC);

SHOW WARNINGS;
CREATE INDEX `opendsa_bookmoduleexercise_752eb95b` ON `opendsa_lti`.`inst_book_section_exercises` (`inst_book_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_bookmoduleexercise_odsa_module_sections1_idx` ON `opendsa_lti`.`inst_book_section_exercises` (`inst_section_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_inst_book_section_exercises_cnf_exercises1_idx` ON `opendsa_lti`.`inst_book_section_exercises` (`cnf_exercise_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_bugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_bugs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_bugs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `os_family` VARCHAR(50) NOT NULL,
  `browser_family` VARCHAR(20) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `screenshot` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_user_interactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_user_interactions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_user_interactions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inst_book_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `inst_section_id` INT(11) NOT NULL,
  `inst_book_section_exercises_id` INT(11) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `action_time` DATETIME NOT NULL,
  `uiid` BIGINT(20) NOT NULL,
  `browser_family` VARCHAR(20) NOT NULL,
  `browser_version` VARCHAR(20) NOT NULL,
  `os_family` VARCHAR(50) NOT NULL,
  `os_version` VARCHAR(20) NOT NULL,
  `device` VARCHAR(50) NOT NULL,
  `ip_address` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_refs_id_5ab2753`
    FOREIGN KEY (`inst_book_id`)
    REFERENCES `opendsa_lti`.`inst_books` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_opendsa_userbutton_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_odsa_user_interactions_odsa_module_sections1`
    FOREIGN KEY (`inst_section_id`)
    REFERENCES `opendsa_lti`.`inst_sections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_odsa_user_interactions_odsa_book_section_exercises1`
    FOREIGN KEY (`inst_book_section_exercises_id`)
    REFERENCES `opendsa_lti`.`inst_book_section_exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `opendsa_userbutton_752eb95b` ON `opendsa_lti`.`odsa_user_interactions` (`inst_book_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_userbutton_users1_idx` ON `opendsa_lti`.`odsa_user_interactions` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_odsa_user_interactions_odsa_module_sections1_idx` ON `opendsa_lti`.`odsa_user_interactions` (`inst_section_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_odsa_user_interactions_odsa_book_section_exercises1_idx` ON `opendsa_lti`.`odsa_user_interactions` (`inst_book_section_exercises_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_book_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_book_progress` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_book_progress` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `book_id` INT(11) NOT NULL,
  `started_exercises` LONGTEXT NOT NULL,
  `all_proficient_exercises` LONGTEXT NOT NULL,
  `users_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_refs_id_2e998b29`
    FOREIGN KEY (`book_id`)
    REFERENCES `opendsa_lti`.`inst_books` (`id`),
  CONSTRAINT `fk_opendsa_userdata_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '# capturing book level student information';

SHOW WARNINGS;
CREATE INDEX `opendsa_userdata_403f60f` ON `opendsa_lti`.`odsa_book_progress` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `opendsa_userdata_752eb95b` ON `opendsa_lti`.`odsa_book_progress` (`book_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_userdata_users1_idx` ON `opendsa_lti`.`odsa_book_progress` (`users_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_exercise_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_exercise_progress` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_exercise_progress` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `streak` INT(11) NOT NULL,
  `longest_streak` INT(11) NOT NULL,
  `first_done` DATETIME NOT NULL,
  `last_done` DATETIME NOT NULL,
  `total_done` INT(11) NOT NULL,
  `total_correct` INT(11) NOT NULL,
  `proficient_date` DATETIME NOT NULL,
  `progress` DECIMAL(5,2) NOT NULL,
  `inst_book_section_exercise_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_opendsa_userexercise_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opendsa_userexercise_opendsa_bookmoduleexercise1`
    FOREIGN KEY (`inst_book_section_exercise_id`)
    REFERENCES `opendsa_lti`.`inst_book_section_exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '# capturing student progress summary for KA and PE exercises, basicllay aggregates all students attempts for one exercise in \"odsa_exercise_attempts\" table in one record.';

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_userexercise_users1_idx` ON `opendsa_lti`.`odsa_exercise_progress` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_userexercise_opendsa_bookmoduleexercise1_idx` ON `opendsa_lti`.`odsa_exercise_progress` (`inst_book_section_exercise_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_exercise_attempts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_exercise_attempts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_exercise_attempts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `inst_book_section_exercise_id` INT(11) NOT NULL,
  `correct` TINYINT(1) NOT NULL,
  `time_done` DATETIME NOT NULL,
  `time_taken` INT(11) NOT NULL,
  `count_hints` INT(11) NOT NULL,
  `hint_used` TINYINT(1) NOT NULL,
  `points_earned` DECIMAL(5,2) NOT NULL,
  `earned_proficiency` TINYINT(1) NOT NULL,
  `count_attempts` BIGINT(20) NOT NULL,
  `ip_address` VARCHAR(20) NOT NULL,
  `ex_question` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_opendsa_userexerciselog_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_opendsa_userexerciselog_opendsa_bookmoduleexercise1`
    FOREIGN KEY (`inst_book_section_exercise_id`)
    REFERENCES `opendsa_lti`.`inst_book_section_exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '# captures KA and PE exercises attempts';

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_userexerciselog_users1_idx` ON `opendsa_lti`.`odsa_exercise_attempts` (`user_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_userexerciselog_opendsa_bookmoduleexercise1_idx` ON `opendsa_lti`.`odsa_exercise_attempts` (`inst_book_section_exercise_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `opendsa_lti`.`odsa_user_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opendsa_lti`.`odsa_user_module` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `opendsa_lti`.`odsa_user_module` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `inst_book_id` INT(11) NOT NULL,
  `inst_module_id` INT(11) NOT NULL,
  `first_done` DATETIME NOT NULL,
  `last_done` DATETIME NOT NULL,
  `proficient_date` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `book_id_refs_id_4a9a3cd7`
    FOREIGN KEY (`inst_book_id`)
    REFERENCES `opendsa_lti`.`inst_books` (`id`),
  CONSTRAINT `module_id_refs_id_24f2d578`
    FOREIGN KEY (`inst_module_id`)
    REFERENCES `opendsa_lti`.`modules` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_opendsa_usermodule_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opendsa_lti`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'captures module level information';

SHOW WARNINGS;
CREATE INDEX `opendsa_usermodule_752eb95b` ON `opendsa_lti`.`odsa_user_module` (`inst_book_id` ASC);

SHOW WARNINGS;
CREATE INDEX `opendsa_usermodule_ac126a2` ON `opendsa_lti`.`odsa_user_module` (`inst_module_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_opendsa_usermodule_users1_idx` ON `opendsa_lti`.`odsa_user_module` (`user_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
