class LearningTool < ActiveRecord::Base

  #~ Relationships ............................................................
  #~ Validation ...............................................................
  #~ Private instance methods .................................................
end