class OdsaExerciseProgress < ActiveRecord::Base
  #~ Relationships ............................................................
  belongs_to :inst_book_section_exercise
  belongs_to :user

  #~ Validation ...............................................................
  #~ Constants ................................................................
  #~ Hooks ....................................................................
  after_initialize :set_defaults, unless: :persisted?
  #~ Class methods ............................................................
  def set_defaults
    self.current_score ||= 0
    self.highest_score ||= 0
    self.total_correct ||= 0
    self.total_worth_credit ||= 0
  end
  #~ Instance methods .........................................................
  #~ Private instance methods .................................................

end

