class OdsaExerciseAttempt < ActiveRecord::Base
  #~ Relationships ............................................................
    belongs_to :user
    belongs_to :inst_book
    belongs_to :inst_section
    belongs_to :inst_book_section_exercise

  #~ Validation ...............................................................
  #~ Constants ................................................................
  #~ Hooks ....................................................................
  #~ Class methods ............................................................
  #~ Instance methods .........................................................
  #~ Private instance methods .................................................

 end
