class OdsaUserInteraction < ActiveRecord::Base
  #~ Relationships ............................................................
  belongs_to :inst_book_section_exercise
  belongs_to :inst_book
  belongs_to :inst_section
  belongs_to :user

  #~ Validation ...............................................................
  #~ Constants ................................................................
  #~ Hooks ....................................................................
  #~ Class methods ............................................................
  #~ Instance methods .........................................................
  #~ Private instance methods .................................................
end
